site_name: Castl.io
site_url: https://example.com/
theme: windmill-dark
nav:
    - Home: index.md
    - Guides:
       - Beginner's Guide: beginners_guide.md
       - Experts's Guide: experts_guide.md
    - Tables:
        - Blocks: blocks.md
        - Items: items.md
        - Mobs: mobs.md
    - Roadmap: roadmap.md
